# Generated by Django 5.1.1 on 2024-10-17 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_blogmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='user_pro',
            fields=[
                ('user_id', models.IntegerField(primary_key=True, serialize=False)),
                ('User_name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='product_use',
            fields=[
                ('pro_id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=100)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myapp.user_pro')),
            ],
        ),
    ]
